### ISSUE TITLE
QA/QC batch error user experience

### ISSUE THREAD

**Issue by nathanielrindlaub** [tnc-ca-geo/animl-api#125]
There are a handful of batch error related user experience details that could use refining:

- [ ] make sure we're indicating to the user if there were Batch.Errors (error records written to `batchErrors` collection ). 
- [ ] Currently when batch errors occur the Batch records are not updated w/ `processingEnd` but they probably should be? 
- [ ] 
- [ ] 

For reference, batch error payloads look like this:
```javascript
{
    "_id": "batch-90274456-d751-4720-935a-a51514ffa673",
    "projectId": "default_project",
    "processingStart": null,
    "processingEnd": null,
    "overrideSerial": null,
    "originalFile": "15-images.zip",
    "uploadedfile": null,
    "total": null,
    "remaining": null,
    "dead": null,
    "imageErrors": 0,
    "errors": [
        {
            "error": "{\"errors\":[{\"message\":\"Variable \\\"$input\\\" got invalid value { _id: \\\"batch-90274456-d751-4720-935a-a51514ffa673\\\", eTag: \\\"4be2b25bda0630c58a0d3021ceb9b8c8\\\", total: 15, processingStart: \\\"2023-08-06T15:38:49.841Z\\\" }; Field \\\"eTag\\\" is not defined by type \\\"UpdateBatchInput\\\".\",\"extensions\":{\"code\":\"BAD_USER_INPUT\",\"exception\":{\"stacktrace\":[\"GraphQLError: Field \\\"eTag\\\" is not defined by type \\\"UpdateBatchInput\\\".\",\"    at coerceInputValueImpl (/var/task/node_modules/graphql/utilities/coerceInputValue.js:134:11)\",\"    at coerceInputValueImpl (/var/task/node_modules/graphql/utilities/coerceInputValue.js:49:14)\",\"    at coerceInputValue (/var/task/node_modules/graphql/utilities/coerceInputValue.js:32:10)\",\"    at coerceVariableValues (/var/task/node_modules/graphql/execution/values.js:132:69)\",\"    at getVariableValues (/var/task/node_modules/graphql/execution/values.js:45:21)\",\"    at buildExecutionContext (/var/task/node_modules/graphql/execution/execute.js:280:63)\",\"    at execute (/var/task/node_modules/graphql/execution/execute.js:116:22)\",\"    at execute (/var/task/node_modules/apollo-server-core/dist/requestPipeline.js:205:48)\",\"    at processGraphQLRequest (/var/task/node_modules/apollo-server-core/dist/requestPipeline.js:148:34)\",\"    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\"]}}}]}\n"
        }
    ]
}
```

**Comment by nathanielrindlaub** [comment]
Related: https://github.com/tnc-ca-geo/animl-frontend/issues/225
