### ISSUE TITLE
Gracefully handle requesting inference on images >4 MB

### ISSUE THREAD

**Issue by nathanielrindlaub** [tnc-ca-geo/animl-api#97]
Sagemaker Serverless Inference max payload size is 4 MB. We should check all images' size before invoking the endpoints, and if the image is too large, resize.

**Comment by nathanielrindlaub** [comment]
The errors look like this:

```ERROR	Error: ValidationError: Request c32b1023-a897-4782-b0f8-b1bedeaeb944 has oversize body.
    at nzdoc (/var/task/src/ml/modelInterfaces.js:202:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async exports.inference (/var/task/src/ml/handler.js:50:26)
```
